# Generated by Django 5.1.7 on 2025-07-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest_rate",
                    models.FloatField(help_text="In percentage, e.g., 12.5"),
                ),
                (
                    "repayment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="vbfinanceapp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "interest_amount_paid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_payments",
                        to="vbfinanceapp.loan",
                    ),
                ),
            ],
        ),
    ]
